import { chromium } from 'playwright';
const GROUND = '/Users/mkbabb/Programming/glass-ui/docs/tranches/AZ/audit/ground';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 }, deviceScaleFactor: 2 });
await page.goto('http://localhost:5199/dock/rail', { waitUntil: 'networkidle' });
await page.evaluate(() => { Object.defineProperty(document,'hidden',{value:true,configurable:true}); document.dispatchEvent(new Event('visibilitychange')); });
await page.waitForTimeout(1500);
await page.screenshot({ path: `${GROUND}/C1-dock-rail-full.png`, fullPage: true });
console.log('rail captured');
await browser.close();
